"""Extract the ASCII wireframes from design/TOKENS.md, check that every framed
line has the same width, and write design/wireframes.js for the token board."""
import json, re, sys, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
md = (root / 'design/TOKENS.md').read_text()
blocks = re.findall(r'<!-- wf:([\w-]+) -->\n```text\n(.*?)```', md, re.S)
bad = 0; out = {}
for key, body in blocks:
    lines = body.rstrip('\n').split('\n')
    framed = [l for l in lines if l[:1] in '┌│├└']
    widths = {len(l) for l in framed}
    if len(widths) != 1:
        bad += 1
        w0 = len(framed[0])
        for i, l in enumerate(lines):
            if l[:1] in '┌│├└' and len(l) != w0: print(f'{key} line {i+1}: {len(l)} vs {w0}: {l}')
    out[key] = body.rstrip('\n')
(root / 'design/wireframes.js').write_text(
  '/* generated by tools/build_wireframes.py from design/TOKENS.md */\n'
  'const WF=' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n'
  'for (const [id, text] of Object.entries(WF)) { const el = document.getElementById(id); if (el) el.textContent = text; }\n')
print(f'{len(blocks)} wireframes, {bad} misaligned'); sys.exit(1 if bad else 0)
