/**
 * Writes supabase/migrations/0001_init.sql from src/data/schema.ts, so the database
 * and the app can never disagree about a column. Run: npx tsx tools/gen_sql.ts
 * (tests/unit/schema-sql.test.ts fails if the file is stale).
 */
import { writeFileSync, readFileSync } from "node:fs";
import { z } from "zod";
import { tables, TABLES, base } from "../src/data/schema";

function unwrap(s: z.ZodType): z.ZodType {
  let cur: z.ZodType = s;
  for (;;) {
    const def = (cur as unknown as { def: { type: string; innerType?: z.ZodType } }).def;
    if ((def.type === "optional" || def.type === "nullable" || def.type === "default") && def.innerType) cur = def.innerType;
    else return cur;
  }
}

function sqlType(col: string, s: z.ZodType): string {
  const u = unwrap(s) as unknown as { def: { type: string; element?: z.ZodType; checks?: { _zod: { def: { check: string; format?: string } } }[] } };
  const t = u.def.type;
  const formats = (u.def.checks ?? []).map((c) => c._zod.def.format ?? c._zod.def.check);
  if (t === "string") {
    if (formats.includes("uuid")) return "uuid";
    if (formats.includes("datetime")) return "timestamptz";
    if (formats.includes("regex") && /(_on|^day|valid_from|valid_to|period_start|deadline|local_day|starts_on|ends_on|first_seen_on)$/.test(col)) return "date";
    if (formats.includes("regex") && /(time|starts_at|ends_at)$/.test(col)) return "time";
    return "text";
  }
  if (t === "enum") return "text";
  if (t === "boolean") return "boolean";
  if (t === "number") return formats.includes("number_format") || /cents|minutes|weekday|day_of_month|interval_days|times_mentioned|width|height|bytes|unpaid_break_min|rev|week_starts_on/.test(col) ? (col === "rev" ? "bigint" : "integer") : "double precision";
  if (t === "array") {
    const el = unwrap(u.def.element!) as unknown as { def: { type: string; checks?: { _zod: { def: { format?: string } } }[] } };
    if (el.def.type === "string") return (el.def.checks ?? []).some((c) => c._zod.def.format === "uuid") ? "uuid[]" : "text[]";
    return "jsonb";
  }
  return "jsonb";
}

const baseCols = Object.keys(base.shape);
let out = `-- generated by tools/gen_sql.ts from src/data/schema.ts; do not edit by hand
-- WAHB'S WORLD schema: one table per synced entity, row level security on every table,
-- a shared revision sequence for incremental pulls, and history of replaced rows.

create schema if not exists wahb;
create sequence if not exists wahb.rev_seq;

create table if not exists wahb.history (
  id bigserial primary key,
  table_name text not null,
  row_id uuid not null,
  user_id uuid,
  old_row jsonb not null,
  replaced_at timestamptz not null default now()
);
create index if not exists history_row on wahb.history (row_id);

-- Every write gets the next revision and the caller as owner.
create or replace function wahb.stamp() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  new.rev := nextval('wahb.rev_seq');
  if auth.uid() is not null then new.user_id := auth.uid(); end if;
  return new;
end $$;

-- Keep the version an update replaces, so a lost edit can be recovered.
create or replace function wahb.keep_history() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into wahb.history (table_name, row_id, user_id, old_row) values (tg_table_name, old.id, old.user_id, to_jsonb(old));
  return new;
end $$;

`;

for (const name of TABLES) {
  const shape = tables[name].shape as Record<string, z.ZodType>;
  const cols = Object.entries(shape).map(([c, s]) => {
    if (c === "id") return "  id uuid primary key";
    if (c === "user_id") return "  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade";
    if (c === "rev") return "  rev bigint not null default 0";
    if (c === "hlc") return '  hlc text collate "C" not null';
    if (c === "device_id") return "  device_id text not null";
    if (c === "created_at" || c === "updated_at") return `  ${c} timestamptz not null`;
    const nullable = s.safeParse(null).success || s.safeParse(undefined).success;
    return `  ${c} ${sqlType(c, s)}${nullable ? "" : " not null"}`;
  });
  // Columns added after a table exists: re-running this file adds them without touching data.
  const additions = Object.entries(shape)
    .filter(([c]) => !baseCols.includes(c))
    .map(([c, s]) => `alter table public.${name} add column if not exists ${c} ${sqlType(c, s)};`)
    .join("\n");
  out += `create table if not exists public.${name} (\n${cols.join(",\n")}\n);
${additions}
create index if not exists ${name}_user_rev on public.${name} (user_id, rev);
alter table public.${name} enable row level security;
drop policy if exists "owner only" on public.${name};
create policy "owner only" on public.${name} for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.${name};
create trigger stamp before insert or update on public.${name} for each row execute function wahb.stamp();
drop trigger if exists history on public.${name};
create trigger history after update on public.${name} for each row execute function wahb.keep_history();
grant select, insert, update on public.${name} to authenticated;

`;
}

out += `-- Tables the sync functions may touch.
create or replace function wahb.synced_tables() returns text[] language sql immutable as $$
  select array[${TABLES.map((t) => `'${t}'`).join(", ")}]
$$;

-- Hybrid clock stamps compare byte by byte (collate "C"), never by locale rules.
-- Push a batch of rows. Per row: stored if its hybrid clock is newer than the server's,
-- otherwise the server's newer row is returned. Runs as the caller, so row level security applies.
create or replace function public.sync_push(changes jsonb) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  ch jsonb; t text; r jsonb; cur jsonb; cols text; result jsonb;
  accepted jsonb := '[]'::jsonb; newer jsonb := '[]'::jsonb;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  for ch in select * from jsonb_array_elements(changes) loop
    t := ch->>'table';
    if not (t = any (wahb.synced_tables())) then raise exception 'unknown table %', t; end if;
    r := (ch->'row') || jsonb_build_object('user_id', auth.uid(), 'rev', 0);
    execute format('select to_jsonb(x) from public.%I x where id = $1', t) into cur using (r->>'id')::uuid;
    if cur is null then
      execute format('insert into public.%I select * from jsonb_populate_record(null::public.%I, $1) returning to_jsonb(%I.*)', t, t, t)
        into result using r;
      accepted := accepted || jsonb_build_object('table', t, 'id', result->>'id', 'hlc', result->>'hlc', 'rev', (result->>'rev')::bigint, 'user_id', result->>'user_id');
    elsif (cur->>'hlc') collate "C" < (r->>'hlc') collate "C" then
      select string_agg(format('%I', column_name), ', ') into cols
        from information_schema.columns where table_schema = 'public' and table_name = t and column_name <> 'id';
      execute format('update public.%I set (%s) = (select %s from jsonb_populate_record(null::public.%I, $1)) where id = $2 returning to_jsonb(%I.*)', t, cols, cols, t, t)
        into result using r, (r->>'id')::uuid;
      accepted := accepted || jsonb_build_object('table', t, 'id', result->>'id', 'hlc', result->>'hlc', 'rev', (result->>'rev')::bigint, 'user_id', result->>'user_id');
    elsif (cur->>'hlc') = (r->>'hlc') then
      accepted := accepted || jsonb_build_object('table', t, 'id', cur->>'id', 'hlc', cur->>'hlc', 'rev', (cur->>'rev')::bigint, 'user_id', cur->>'user_id');
    else
      newer := newer || jsonb_build_object('table', t, 'row', cur);
    end if;
  end loop;
  return jsonb_build_object('accepted', accepted, 'newer', newer);
end $$;

-- Everything with a revision above \`since\`, oldest first, across all tables.
create or replace function public.sync_pull(since bigint, max_rows integer default 500) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  t text; chunk jsonb; all_rows jsonb := '[]'::jsonb; total integer; picked jsonb; top bigint;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  foreach t in array wahb.synced_tables() loop
    execute format('select coalesce(jsonb_agg(jsonb_build_object(''table'', %L, ''row'', to_jsonb(x)) order by x.rev), ''[]''::jsonb)
      from (select * from public.%I where rev > $1 order by rev limit $2) x', t, t)
      into chunk using since, max_rows + 1;
    all_rows := all_rows || chunk;
  end loop;
  total := jsonb_array_length(all_rows);
  select coalesce(jsonb_agg(e order by (e->'row'->>'rev')::bigint), '[]'::jsonb) into picked
    from (select e from jsonb_array_elements(all_rows) e order by (e->'row'->>'rev')::bigint limit max_rows) s;
  top := coalesce((select max((e->'row'->>'rev')::bigint) from jsonb_array_elements(picked) e), since);
  return jsonb_build_object('changes', picked, 'max_rev', top, 'more', total > max_rows);
end $$;

grant usage on schema wahb to authenticated;
grant usage on sequence wahb.rev_seq to authenticated;
grant execute on function wahb.synced_tables() to authenticated;
grant execute on function public.sync_push(jsonb) to authenticated;
grant execute on function public.sync_pull(bigint, integer) to authenticated;
revoke execute on function public.sync_push(jsonb) from anon;
revoke execute on function public.sync_pull(bigint, integer) from anon;
`;

const path = "supabase/migrations/0001_init.sql";
if (process.argv.includes("--check")) {
  const same = readFileSync(path, "utf8") === out;
  console.log(same ? "0001_init.sql up to date" : "0001_init.sql is stale: run npx tsx tools/gen_sql.ts");
  process.exit(same ? 0 : 1);
}
writeFileSync(path, out);
console.log("wrote", path, TABLES.length, "tables");
