"""Write src/styles/tokens.css from design/tokens.json, so colors have one source.
Run after any change to tokens.json (CI checks the file is up to date)."""
import json, pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
T = json.loads((root / 'design/tokens.json').read_text())
kebab = lambda s: re.sub(r'(?<!^)(?=[A-Z])', '-', s).lower()
def rgb(h): h = h.lstrip('#'); return ' '.join(str(int(h[i:i+2], 16)) for i in (0, 2, 4))
lines = ['/* generated by tools/gen_tokens.py from design/tokens.json; do not edit by hand */', '@theme static {']
for k, v in T['color'].items():
    lines.append(f'  --color-{kebab(k)}: {v};')
lines.append('}')
lines.append(':root {')
for k, v in T['color'].items():
    lines.append(f'  --rgb-{kebab(k)}: {rgb(v)};')
for name, b in T['backings'].items():
    lines.append(f'  --backing-{kebab(name)}: rgb({rgb(T["color"][b["color"]])} / {b["alpha"]});')
lines.append('}')
out = '\n'.join(lines) + '\n'
dest = root / 'src/styles/tokens.css'
if '--check' in sys.argv:
    ok = dest.exists() and dest.read_text() == out
    print('tokens.css up to date' if ok else 'tokens.css is stale: run python3 tools/gen_tokens.py'); sys.exit(0 if ok else 1)
dest.write_text(out); print('wrote', dest.relative_to(root))
