"""Write src/styles/tokens.css from design/tokens.json: light values on :root, dark values under
prefers-color-scheme and [data-theme="dark"]. Run after any change (CI checks it is up to date)."""
import json, pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
T = json.loads((root / 'design/tokens.json').read_text())
kebab = lambda s: re.sub(r'(?<!^)(?=[A-Z])', '-', s).lower()
def rgb(h): h = h.lstrip('#'); return ' '.join(str(int(h[i:i+2], 16)) for i in (0, 2, 4))
def block(mode):
    return '\n'.join(f'  --{kebab(k)}: {v};\n  --{kebab(k)}-rgb: {rgb(v)};' for k, v in T[mode].items())
names = list(T['light'].keys())
out = ['/* generated by tools/gen_tokens.py from design/tokens.json; do not edit by hand */',
       '@theme inline {', *[f'  --color-{kebab(k)}: var(--{kebab(k)});' for k in names], '}',
       ':root {', '  color-scheme: light;', block('light'), '}',
       '@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', '    color-scheme: dark;',
       '\n'.join('  ' + l for l in block('dark').split('\n')), '  }', '}',
       ':root[data-theme="dark"] {', '  color-scheme: dark;', block('dark'), '}']
text = '\n'.join(out) + '\n'
dest = root / 'src/styles/tokens.css'
if '--check' in sys.argv:
    ok = dest.exists() and dest.read_text() == text
    print('tokens.css up to date' if ok else 'tokens.css is stale: run python3 tools/gen_tokens.py'); sys.exit(0 if ok else 1)
dest.write_text(text); print('wrote', dest.relative_to(root))
