-- generated by tools/gen_sql.ts from src/data/schema.ts; do not edit by hand
-- WAHB'S WORLD schema: one table per synced entity, row level security on every table,
-- a shared revision sequence for incremental pulls, and history of replaced rows.

create schema if not exists wahb;
create sequence if not exists wahb.rev_seq;

create table if not exists wahb.history (
  id bigserial primary key,
  table_name text not null,
  row_id uuid not null,
  user_id uuid,
  old_row jsonb not null,
  replaced_at timestamptz not null default now()
);
create index if not exists history_row on wahb.history (row_id);

-- Every write gets the next revision and the caller as owner.
create or replace function wahb.stamp() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  new.rev := nextval('wahb.rev_seq');
  if auth.uid() is not null then new.user_id := auth.uid(); end if;
  return new;
end $$;

-- Keep the version an update replaces, so a lost edit can be recovered.
create or replace function wahb.keep_history() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into wahb.history (table_name, row_id, user_id, old_row) values (tg_table_name, old.id, old.user_id, to_jsonb(old));
  return new;
end $$;

create table if not exists public.days (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  day date not null,
  one_thing text,
  one_thing_ref text,
  mood double precision,
  energy double precision,
  note text
);
create index if not exists days_user_rev on public.days (user_id, rev);
alter table public.days enable row level security;
drop policy if exists "owner only" on public.days;
create policy "owner only" on public.days for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.days;
create trigger stamp before insert or update on public.days for each row execute function wahb.stamp();
drop trigger if exists history on public.days;
create trigger history after update on public.days for each row execute function wahb.keep_history();
grant select, insert, update on public.days to authenticated;

create table if not exists public.checkins (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  occurred_at timestamptz not null,
  local_day date not null,
  kind text not null,
  ref_table text,
  ref_id uuid,
  payload jsonb
);
create index if not exists checkins_user_rev on public.checkins (user_id, rev);
alter table public.checkins enable row level security;
drop policy if exists "owner only" on public.checkins;
create policy "owner only" on public.checkins for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.checkins;
create trigger stamp before insert or update on public.checkins for each row execute function wahb.stamp();
drop trigger if exists history on public.checkins;
create trigger history after update on public.checkins for each row execute function wahb.keep_history();
grant select, insert, update on public.checkins to authenticated;

create table if not exists public.tasks (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  title text not null,
  area text,
  due_on date,
  done_at timestamptz,
  priority text,
  course_id uuid,
  project_id uuid,
  resource_id uuid,
  notes text
);
create index if not exists tasks_user_rev on public.tasks (user_id, rev);
alter table public.tasks enable row level security;
drop policy if exists "owner only" on public.tasks;
create policy "owner only" on public.tasks for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.tasks;
create trigger stamp before insert or update on public.tasks for each row execute function wahb.stamp();
drop trigger if exists history on public.tasks;
create trigger history after update on public.tasks for each row execute function wahb.keep_history();
grant select, insert, update on public.tasks to authenticated;

create table if not exists public.resources (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  title text not null,
  publisher text not null,
  url text not null,
  summary text,
  area text not null,
  verified_on date,
  link_status text,
  link_checked_at timestamptz
);
create index if not exists resources_user_rev on public.resources (user_id, rev);
alter table public.resources enable row level security;
drop policy if exists "owner only" on public.resources;
create policy "owner only" on public.resources for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.resources;
create trigger stamp before insert or update on public.resources for each row execute function wahb.stamp();
drop trigger if exists history on public.resources;
create trigger history after update on public.resources for each row execute function wahb.keep_history();
grant select, insert, update on public.resources to authenticated;

create table if not exists public.settings (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  motion text,
  intensity_cap text,
  sound_profile text,
  volume double precision,
  week_starts_on integer,
  hours_warning boolean
);
create index if not exists settings_user_rev on public.settings (user_id, rev);
alter table public.settings enable row level security;
drop policy if exists "owner only" on public.settings;
create policy "owner only" on public.settings for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.settings;
create trigger stamp before insert or update on public.settings for each row execute function wahb.stamp();
drop trigger if exists history on public.settings;
create trigger history after update on public.settings for each row execute function wahb.keep_history();
grant select, insert, update on public.settings to authenticated;

create table if not exists public.chapters (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  period_kind text not null,
  period_start date not null,
  title text,
  note text,
  cover_photo_id uuid
);
create index if not exists chapters_user_rev on public.chapters (user_id, rev);
alter table public.chapters enable row level security;
drop policy if exists "owner only" on public.chapters;
create policy "owner only" on public.chapters for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.chapters;
create trigger stamp before insert or update on public.chapters for each row execute function wahb.stamp();
drop trigger if exists history on public.chapters;
create trigger history after update on public.chapters for each row execute function wahb.keep_history();
grant select, insert, update on public.chapters to authenticated;

create table if not exists public.terms (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  kind text,
  starts_on date not null,
  ends_on date not null,
  status text
);
create index if not exists terms_user_rev on public.terms (user_id, rev);
alter table public.terms enable row level security;
drop policy if exists "owner only" on public.terms;
create policy "owner only" on public.terms for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.terms;
create trigger stamp before insert or update on public.terms for each row execute function wahb.stamp();
drop trigger if exists history on public.terms;
create trigger history after update on public.terms for each row execute function wahb.keep_history();
grant select, insert, update on public.terms to authenticated;

create table if not exists public.term_breaks (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  term_id uuid not null,
  name text not null,
  starts_on date not null,
  ends_on date not null
);
create index if not exists term_breaks_user_rev on public.term_breaks (user_id, rev);
alter table public.term_breaks enable row level security;
drop policy if exists "owner only" on public.term_breaks;
create policy "owner only" on public.term_breaks for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.term_breaks;
create trigger stamp before insert or update on public.term_breaks for each row execute function wahb.stamp();
drop trigger if exists history on public.term_breaks;
create trigger history after update on public.term_breaks for each row execute function wahb.keep_history();
grant select, insert, update on public.term_breaks to authenticated;

create table if not exists public.courses (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  term_id uuid not null,
  code text not null,
  name text not null,
  professor text,
  language text,
  retake boolean,
  topics text[],
  links jsonb,
  notes text
);
create index if not exists courses_user_rev on public.courses (user_id, rev);
alter table public.courses enable row level security;
drop policy if exists "owner only" on public.courses;
create policy "owner only" on public.courses for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.courses;
create trigger stamp before insert or update on public.courses for each row execute function wahb.stamp();
drop trigger if exists history on public.courses;
create trigger history after update on public.courses for each row execute function wahb.keep_history();
grant select, insert, update on public.courses to authenticated;

create table if not exists public.schedule_blocks (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  term_id uuid,
  course_id uuid,
  kind text not null,
  title text not null,
  weekday integer not null,
  starts_at time not null,
  ends_at time not null,
  location text,
  valid_from date,
  valid_to date
);
create index if not exists schedule_blocks_user_rev on public.schedule_blocks (user_id, rev);
alter table public.schedule_blocks enable row level security;
drop policy if exists "owner only" on public.schedule_blocks;
create policy "owner only" on public.schedule_blocks for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.schedule_blocks;
create trigger stamp before insert or update on public.schedule_blocks for each row execute function wahb.stamp();
drop trigger if exists history on public.schedule_blocks;
create trigger history after update on public.schedule_blocks for each row execute function wahb.keep_history();
grant select, insert, update on public.schedule_blocks to authenticated;

create table if not exists public.assessments (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  course_id uuid,
  project_id uuid,
  title text not null,
  kind text,
  due_on date,
  due_time time,
  weight double precision,
  covers text[],
  status text,
  grade double precision,
  grade_out_of double precision,
  notes text
);
create index if not exists assessments_user_rev on public.assessments (user_id, rev);
alter table public.assessments enable row level security;
drop policy if exists "owner only" on public.assessments;
create policy "owner only" on public.assessments for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.assessments;
create trigger stamp before insert or update on public.assessments for each row execute function wahb.stamp();
drop trigger if exists history on public.assessments;
create trigger history after update on public.assessments for each row execute function wahb.keep_history();
grant select, insert, update on public.assessments to authenticated;

create table if not exists public.employers (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  hourly_cents integer,
  tips_estimate_cents integer,
  deduction_rate double precision
);
create index if not exists employers_user_rev on public.employers (user_id, rev);
alter table public.employers enable row level security;
drop policy if exists "owner only" on public.employers;
create policy "owner only" on public.employers for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.employers;
create trigger stamp before insert or update on public.employers for each row execute function wahb.stamp();
drop trigger if exists history on public.employers;
create trigger history after update on public.employers for each row execute function wahb.keep_history();
grant select, insert, update on public.employers to authenticated;

create table if not exists public.shifts (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  employer_id uuid,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  unpaid_break_min integer,
  status text,
  rush jsonb,
  pay_cents integer,
  tips_cents integer,
  notes text
);
create index if not exists shifts_user_rev on public.shifts (user_id, rev);
alter table public.shifts enable row level security;
drop policy if exists "owner only" on public.shifts;
create policy "owner only" on public.shifts for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.shifts;
create trigger stamp before insert or update on public.shifts for each row execute function wahb.stamp();
drop trigger if exists history on public.shifts;
create trigger history after update on public.shifts for each row execute function wahb.keep_history();
grant select, insert, update on public.shifts to authenticated;

create table if not exists public.accounts (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  kind text not null,
  is_own boolean
);
create index if not exists accounts_user_rev on public.accounts (user_id, rev);
alter table public.accounts enable row level security;
drop policy if exists "owner only" on public.accounts;
create policy "owner only" on public.accounts for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.accounts;
create trigger stamp before insert or update on public.accounts for each row execute function wahb.stamp();
drop trigger if exists history on public.accounts;
create trigger history after update on public.accounts for each row execute function wahb.keep_history();
grant select, insert, update on public.accounts to authenticated;

create table if not exists public.categories (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  group_name text not null,
  name text not null,
  kind text,
  monthly_budget_cents integer,
  archived boolean
);
create index if not exists categories_user_rev on public.categories (user_id, rev);
alter table public.categories enable row level security;
drop policy if exists "owner only" on public.categories;
create policy "owner only" on public.categories for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.categories;
create trigger stamp before insert or update on public.categories for each row execute function wahb.stamp();
drop trigger if exists history on public.categories;
create trigger history after update on public.categories for each row execute function wahb.keep_history();
grant select, insert, update on public.categories to authenticated;

create table if not exists public.recurring_bills (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  amount_cents integer not null,
  day_of_month integer not null,
  category_id uuid,
  account_id uuid,
  active boolean
);
create index if not exists recurring_bills_user_rev on public.recurring_bills (user_id, rev);
alter table public.recurring_bills enable row level security;
drop policy if exists "owner only" on public.recurring_bills;
create policy "owner only" on public.recurring_bills for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.recurring_bills;
create trigger stamp before insert or update on public.recurring_bills for each row execute function wahb.stamp();
drop trigger if exists history on public.recurring_bills;
create trigger history after update on public.recurring_bills for each row execute function wahb.keep_history();
grant select, insert, update on public.recurring_bills to authenticated;

create table if not exists public.transactions (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  occurred_on date not null,
  amount_cents integer not null,
  direction text not null,
  account_id uuid,
  to_account_id uuid,
  category_id uuid,
  merchant text,
  note text,
  goal_id uuid,
  memory_id uuid,
  source text
);
create index if not exists transactions_user_rev on public.transactions (user_id, rev);
alter table public.transactions enable row level security;
drop policy if exists "owner only" on public.transactions;
create policy "owner only" on public.transactions for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.transactions;
create trigger stamp before insert or update on public.transactions for each row execute function wahb.stamp();
drop trigger if exists history on public.transactions;
create trigger history after update on public.transactions for each row execute function wahb.keep_history();
grant select, insert, update on public.transactions to authenticated;

create table if not exists public.goals (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  kind text not null,
  name text not null,
  target_cents integer,
  target_value double precision,
  due_on date,
  term_id uuid,
  notes text
);
create index if not exists goals_user_rev on public.goals (user_id, rev);
alter table public.goals enable row level security;
drop policy if exists "owner only" on public.goals;
create policy "owner only" on public.goals for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.goals;
create trigger stamp before insert or update on public.goals for each row execute function wahb.stamp();
drop trigger if exists history on public.goals;
create trigger history after update on public.goals for each row execute function wahb.keep_history();
grant select, insert, update on public.goals to authenticated;

create table if not exists public.projects (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  title text not null,
  type text not null,
  stage text,
  objective text,
  success text,
  deadline date,
  weekly_hours double precision,
  course_id uuid,
  notes text
);
create index if not exists projects_user_rev on public.projects (user_id, rev);
alter table public.projects enable row level security;
drop policy if exists "owner only" on public.projects;
create policy "owner only" on public.projects for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.projects;
create trigger stamp before insert or update on public.projects for each row execute function wahb.stamp();
drop trigger if exists history on public.projects;
create trigger history after update on public.projects for each row execute function wahb.keep_history();
grant select, insert, update on public.projects to authenticated;

create table if not exists public.project_tasks (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  project_id uuid not null,
  title text not null,
  deliverable text,
  due_on date,
  estimate_hours double precision,
  kind text,
  priority text,
  status text,
  depends_on uuid[],
  done_at timestamptz
);
create index if not exists project_tasks_user_rev on public.project_tasks (user_id, rev);
alter table public.project_tasks enable row level security;
drop policy if exists "owner only" on public.project_tasks;
create policy "owner only" on public.project_tasks for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.project_tasks;
create trigger stamp before insert or update on public.project_tasks for each row execute function wahb.stamp();
drop trigger if exists history on public.project_tasks;
create trigger history after update on public.project_tasks for each row execute function wahb.keep_history();
grant select, insert, update on public.project_tasks to authenticated;

create table if not exists public.project_sessions (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  project_id uuid not null,
  started_at timestamptz not null,
  minutes integer not null,
  kind text,
  note text
);
create index if not exists project_sessions_user_rev on public.project_sessions (user_id, rev);
alter table public.project_sessions enable row level security;
drop policy if exists "owner only" on public.project_sessions;
create policy "owner only" on public.project_sessions for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.project_sessions;
create trigger stamp before insert or update on public.project_sessions for each row execute function wahb.stamp();
drop trigger if exists history on public.project_sessions;
create trigger history after update on public.project_sessions for each row execute function wahb.keep_history();
grant select, insert, update on public.project_sessions to authenticated;

create table if not exists public.project_logs (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  project_id uuid not null,
  kind text not null,
  body text not null,
  occurred_on date not null
);
create index if not exists project_logs_user_rev on public.project_logs (user_id, rev);
alter table public.project_logs enable row level security;
drop policy if exists "owner only" on public.project_logs;
create policy "owner only" on public.project_logs for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.project_logs;
create trigger stamp before insert or update on public.project_logs for each row execute function wahb.stamp();
drop trigger if exists history on public.project_logs;
create trigger history after update on public.project_logs for each row execute function wahb.keep_history();
grant select, insert, update on public.project_logs to authenticated;

create table if not exists public.applications (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  organization text not null,
  role text not null,
  location text,
  url text,
  season text,
  status text,
  applied_on date,
  next_step text,
  next_step_on date,
  notes text
);
create index if not exists applications_user_rev on public.applications (user_id, rev);
alter table public.applications enable row level security;
drop policy if exists "owner only" on public.applications;
create policy "owner only" on public.applications for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.applications;
create trigger stamp before insert or update on public.applications for each row execute function wahb.stamp();
drop trigger if exists history on public.applications;
create trigger history after update on public.applications for each row execute function wahb.keep_history();
grant select, insert, update on public.applications to authenticated;

create table if not exists public.evidence (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  title text not null,
  kind text not null,
  project_id uuid,
  url text,
  description text,
  occurred_on date
);
create index if not exists evidence_user_rev on public.evidence (user_id, rev);
alter table public.evidence enable row level security;
drop policy if exists "owner only" on public.evidence;
create policy "owner only" on public.evidence for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.evidence;
create trigger stamp before insert or update on public.evidence for each row execute function wahb.stamp();
drop trigger if exists history on public.evidence;
create trigger history after update on public.evidence for each row execute function wahb.keep_history();
grant select, insert, update on public.evidence to authenticated;

create table if not exists public.skills (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  notes text
);
create index if not exists skills_user_rev on public.skills (user_id, rev);
alter table public.skills enable row level security;
drop policy if exists "owner only" on public.skills;
create policy "owner only" on public.skills for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.skills;
create trigger stamp before insert or update on public.skills for each row execute function wahb.stamp();
drop trigger if exists history on public.skills;
create trigger history after update on public.skills for each row execute function wahb.keep_history();
grant select, insert, update on public.skills to authenticated;

create table if not exists public.evidence_skills (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  evidence_id uuid not null,
  skill_id uuid not null
);
create index if not exists evidence_skills_user_rev on public.evidence_skills (user_id, rev);
alter table public.evidence_skills enable row level security;
drop policy if exists "owner only" on public.evidence_skills;
create policy "owner only" on public.evidence_skills for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.evidence_skills;
create trigger stamp before insert or update on public.evidence_skills for each row execute function wahb.stamp();
drop trigger if exists history on public.evidence_skills;
create trigger history after update on public.evidence_skills for each row execute function wahb.keep_history();
grant select, insert, update on public.evidence_skills to authenticated;

create table if not exists public.stories (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  title text not null,
  situation text,
  action text,
  result text,
  lesson text,
  evidence_ids uuid[]
);
create index if not exists stories_user_rev on public.stories (user_id, rev);
alter table public.stories enable row level security;
drop policy if exists "owner only" on public.stories;
create policy "owner only" on public.stories for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.stories;
create trigger stamp before insert or update on public.stories for each row execute function wahb.stamp();
drop trigger if exists history on public.stories;
create trigger history after update on public.stories for each row execute function wahb.keep_history();
grant select, insert, update on public.stories to authenticated;

create table if not exists public.linkedin_drafts (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  section text not null,
  body text,
  resource_id uuid
);
create index if not exists linkedin_drafts_user_rev on public.linkedin_drafts (user_id, rev);
alter table public.linkedin_drafts enable row level security;
drop policy if exists "owner only" on public.linkedin_drafts;
create policy "owner only" on public.linkedin_drafts for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.linkedin_drafts;
create trigger stamp before insert or update on public.linkedin_drafts for each row execute function wahb.stamp();
drop trigger if exists history on public.linkedin_drafts;
create trigger history after update on public.linkedin_drafts for each row execute function wahb.keep_history();
grant select, insert, update on public.linkedin_drafts to authenticated;

create table if not exists public.term_plans (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  term_label text not null,
  option text not null,
  probability double precision,
  note text
);
create index if not exists term_plans_user_rev on public.term_plans (user_id, rev);
alter table public.term_plans enable row level security;
drop policy if exists "owner only" on public.term_plans;
create policy "owner only" on public.term_plans for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.term_plans;
create trigger stamp before insert or update on public.term_plans for each row execute function wahb.stamp();
drop trigger if exists history on public.term_plans;
create trigger history after update on public.term_plans for each row execute function wahb.keep_history();
grant select, insert, update on public.term_plans to authenticated;

create table if not exists public.knowledge_entries (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  topic text not null,
  learned text,
  source_title text,
  source_url text not null,
  why_it_matters text,
  questions text,
  review_on date,
  interval_days integer,
  ease double precision,
  changed_mind boolean,
  rabbit_hole boolean,
  course_id uuid
);
create index if not exists knowledge_entries_user_rev on public.knowledge_entries (user_id, rev);
alter table public.knowledge_entries enable row level security;
drop policy if exists "owner only" on public.knowledge_entries;
create policy "owner only" on public.knowledge_entries for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.knowledge_entries;
create trigger stamp before insert or update on public.knowledge_entries for each row execute function wahb.stamp();
drop trigger if exists history on public.knowledge_entries;
create trigger history after update on public.knowledge_entries for each row execute function wahb.keep_history();
grant select, insert, update on public.knowledge_entries to authenticated;

create table if not exists public.knowledge_links (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  from_id uuid not null,
  to_id uuid not null
);
create index if not exists knowledge_links_user_rev on public.knowledge_links (user_id, rev);
alter table public.knowledge_links enable row level security;
drop policy if exists "owner only" on public.knowledge_links;
create policy "owner only" on public.knowledge_links for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.knowledge_links;
create trigger stamp before insert or update on public.knowledge_links for each row execute function wahb.stamp();
drop trigger if exists history on public.knowledge_links;
create trigger history after update on public.knowledge_links for each row execute function wahb.keep_history();
grant select, insert, update on public.knowledge_links to authenticated;

create table if not exists public.training_sessions (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  occurred_on date not null,
  kind text,
  minutes integer,
  notes text
);
create index if not exists training_sessions_user_rev on public.training_sessions (user_id, rev);
alter table public.training_sessions enable row level security;
drop policy if exists "owner only" on public.training_sessions;
create policy "owner only" on public.training_sessions for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.training_sessions;
create trigger stamp before insert or update on public.training_sessions for each row execute function wahb.stamp();
drop trigger if exists history on public.training_sessions;
create trigger history after update on public.training_sessions for each row execute function wahb.keep_history();
grant select, insert, update on public.training_sessions to authenticated;

create table if not exists public.memories (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  occurred_on date not null,
  title text not null,
  body text,
  kind text,
  place text,
  people text[]
);
create index if not exists memories_user_rev on public.memories (user_id, rev);
alter table public.memories enable row level security;
drop policy if exists "owner only" on public.memories;
create policy "owner only" on public.memories for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.memories;
create trigger stamp before insert or update on public.memories for each row execute function wahb.stamp();
drop trigger if exists history on public.memories;
create trigger history after update on public.memories for each row execute function wahb.keep_history();
grant select, insert, update on public.memories to authenticated;

create table if not exists public.people (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  name text not null,
  first_seen_on date not null,
  times_mentioned integer
);
create index if not exists people_user_rev on public.people (user_id, rev);
alter table public.people enable row level security;
drop policy if exists "owner only" on public.people;
create policy "owner only" on public.people for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.people;
create trigger stamp before insert or update on public.people for each row execute function wahb.stamp();
drop trigger if exists history on public.people;
create trigger history after update on public.people for each row execute function wahb.keep_history();
grant select, insert, update on public.people to authenticated;

create table if not exists public.photos (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  hlc text collate "C" not null,
  deleted_at timestamptz,
  rev bigint not null default 0,
  device_id text not null,
  memory_id uuid,
  storage_path text,
  width integer,
  height integer,
  bytes integer,
  blurhash text,
  taken_at timestamptz
);
create index if not exists photos_user_rev on public.photos (user_id, rev);
alter table public.photos enable row level security;
drop policy if exists "owner only" on public.photos;
create policy "owner only" on public.photos for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop trigger if exists stamp on public.photos;
create trigger stamp before insert or update on public.photos for each row execute function wahb.stamp();
drop trigger if exists history on public.photos;
create trigger history after update on public.photos for each row execute function wahb.keep_history();
grant select, insert, update on public.photos to authenticated;

-- Tables the sync functions may touch.
create or replace function wahb.synced_tables() returns text[] language sql immutable as $$
  select array['days', 'checkins', 'tasks', 'resources', 'settings', 'chapters', 'terms', 'term_breaks', 'courses', 'schedule_blocks', 'assessments', 'employers', 'shifts', 'accounts', 'categories', 'recurring_bills', 'transactions', 'goals', 'projects', 'project_tasks', 'project_sessions', 'project_logs', 'applications', 'evidence', 'skills', 'evidence_skills', 'stories', 'linkedin_drafts', 'term_plans', 'knowledge_entries', 'knowledge_links', 'training_sessions', 'memories', 'people', 'photos']
$$;

-- Hybrid clock stamps compare byte by byte (collate "C"), never by locale rules.
-- Push a batch of rows. Per row: stored if its hybrid clock is newer than the server's,
-- otherwise the server's newer row is returned. Runs as the caller, so row level security applies.
create or replace function public.sync_push(changes jsonb) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  ch jsonb; t text; r jsonb; cur jsonb; cols text; result jsonb;
  accepted jsonb := '[]'::jsonb; newer jsonb := '[]'::jsonb;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  for ch in select * from jsonb_array_elements(changes) loop
    t := ch->>'table';
    if not (t = any (wahb.synced_tables())) then raise exception 'unknown table %', t; end if;
    r := (ch->'row') || jsonb_build_object('user_id', auth.uid(), 'rev', 0);
    execute format('select to_jsonb(x) from public.%I x where id = $1', t) into cur using (r->>'id')::uuid;
    if cur is null then
      execute format('insert into public.%I select * from jsonb_populate_record(null::public.%I, $1) returning to_jsonb(%I.*)', t, t, t)
        into result using r;
      accepted := accepted || jsonb_build_object('table', t, 'id', result->>'id', 'hlc', result->>'hlc', 'rev', (result->>'rev')::bigint, 'user_id', result->>'user_id');
    elsif (cur->>'hlc') collate "C" < (r->>'hlc') collate "C" then
      select string_agg(format('%I', column_name), ', ') into cols
        from information_schema.columns where table_schema = 'public' and table_name = t and column_name <> 'id';
      execute format('update public.%I set (%s) = (select %s from jsonb_populate_record(null::public.%I, $1)) where id = $2 returning to_jsonb(%I.*)', t, cols, cols, t, t)
        into result using r, (r->>'id')::uuid;
      accepted := accepted || jsonb_build_object('table', t, 'id', result->>'id', 'hlc', result->>'hlc', 'rev', (result->>'rev')::bigint, 'user_id', result->>'user_id');
    elsif (cur->>'hlc') = (r->>'hlc') then
      accepted := accepted || jsonb_build_object('table', t, 'id', cur->>'id', 'hlc', cur->>'hlc', 'rev', (cur->>'rev')::bigint, 'user_id', cur->>'user_id');
    else
      newer := newer || jsonb_build_object('table', t, 'row', cur);
    end if;
  end loop;
  return jsonb_build_object('accepted', accepted, 'newer', newer);
end $$;

-- Everything with a revision above `since`, oldest first, across all tables.
create or replace function public.sync_pull(since bigint, max_rows integer default 500) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  t text; chunk jsonb; all_rows jsonb := '[]'::jsonb; total integer; picked jsonb; top bigint;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  foreach t in array wahb.synced_tables() loop
    execute format('select coalesce(jsonb_agg(jsonb_build_object(''table'', %L, ''row'', to_jsonb(x)) order by x.rev), ''[]''::jsonb)
      from (select * from public.%I where rev > $1 order by rev limit $2) x', t, t)
      into chunk using since, max_rows + 1;
    all_rows := all_rows || chunk;
  end loop;
  total := jsonb_array_length(all_rows);
  select coalesce(jsonb_agg(e order by (e->'row'->>'rev')::bigint), '[]'::jsonb) into picked
    from (select e from jsonb_array_elements(all_rows) e order by (e->'row'->>'rev')::bigint limit max_rows) s;
  top := coalesce((select max((e->'row'->>'rev')::bigint) from jsonb_array_elements(picked) e), since);
  return jsonb_build_object('changes', picked, 'max_rev', top, 'more', total > max_rows);
end $$;

grant usage on schema wahb to authenticated;
grant usage on sequence wahb.rev_seq to authenticated;
grant execute on function wahb.synced_tables() to authenticated;
grant execute on function public.sync_push(jsonb) to authenticated;
grant execute on function public.sync_pull(bigint, integer) to authenticated;
revoke execute on function public.sync_push(jsonb) from anon;
revoke execute on function public.sync_pull(bigint, integer) from anon;
